import { Montserrat } from '@next/font/google';

import Nav from '@/components/Nav';
import classNames from '@/utils/classNames';

import './globals.css';

const montserrat = Montserrat({ subsets: ['latin'] });

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html
      lang="en"
      className={classNames(
        montserrat.className,
        'bg-gray-100 text-base text-gray-700'
      )}
    >
      <body>
        <Nav />
        {children}
      </body>
    </html>
  );
}
